.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MOODNS" "1" "August 2014" "" ""
.
.SH "NAME"
\fBmoodns\fR \- minimal multicast DNS server
.
.SH "SYNOPSIS"
\fBmoodns [OPTIONS]\fR
.
.SH "DESCRIPTION"
\fBmoodns\fR is a server implementation of multicast DNS\. Multicast DNS allows programs to discover hosts running on a local network by using familiar DNS programming interfaces without the need for a conventional DNS server\.
.
.SH "OPTIONS"
\fB\-H, \-\-host\fR
.
.P
\~\~\~\~\~\~ Name of the local host\. If no name is provided, moodns will retrieve the local computer hostname\.
.
.P
\fB\-l, \-\-listen\fR
.
.P
\~\~\~\~\~\~ Listen on this address:port [default: 0\.0\.0\.0:5353]\. Multiple <address:port> comma\-separated tuples can be provided\.
.
.P
\fB\-r, \-\-enable\-multicast\-forward\fR
.
.P
\~\~\~\~\~\~ Enable forwarding of unicast requests to multicast (enable at your own risk)\.
.
.P
\fB\-s, \-\-silent\fR
.
.P
\~\~\~\~\~\~ Print fatal errors only\.
.
.P
\fB\-h, \-\-help\fR
.
.P
\~\~\~\~\~\~ Show the program\'s help message and exit\.
.
.SH "AUTHOR"
Alessandro Ghedini \fIalessandro@ghedini\.me\fR
.
.SH "COPYRIGHT"
Copyright (C) 2014 Alessandro Ghedini \fIalessandro@ghedini\.me\fR
.
.P
This program is released under the 2 clause BSD license\.
